info :
#   id : spring-boot-admin
#   version : @project.version@
   stage : test
   build :
#      artifact : @project.artifactId@
#      name : @project.name@
#      description : @project.description@
#      version : @project.version@


logging:
  file: logs/app.log

spring:
  application:
     name: mobile-rtr
     admin:
       enabled: true
  profiles:
    active: dev
  boot:
    admin:
      url: http://localhost:8080
  cloud:
    config:
      enabled: false

endpoints :
    health :
        sensitive : false
    logfile :
      enabled : true
      sensitive : false

management:
  context-path: /manage